[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/api"
to = "/.netlify/functions/api"
status = 200

# Si tu Angular es SPA, agrega también:
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
